"""Comprehensive report generator for evaluation results.

Generate detailed analysis reports with insights and recommendations.
"""

from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional


class ReportGenerator:
    """Generate comprehensive evaluation reports.

    Creates detailed Markdown and HTML reports with analysis,
    insights, and recommendations based on evaluation results.

    Examples
    --------
    >>> from semeval import TaskRunner, SentenceTransformerEncoder
    >>> from semeval.postprocess import ReportGenerator
    >>>
    >>> # Run evaluation
    >>> encoder = SentenceTransformerEncoder("model-name")
    >>> runner = TaskRunner(encoder=encoder)
    >>> result = runner.run("data/test_data.json")
    >>>
    >>> # Generate comprehensive report
    >>> generator = ReportGenerator()
    >>> generator.generate_report(result, "reports/analysis.md", model_name="my-model")
    """

    def generate_report(
        self,
        result,
        output_path: str,
        model_name: Optional[str] = None,
        include_recommendations: bool = True,
    ) -> None:
        """Generate comprehensive Markdown report.

        Parameters
        ----------
        result : EvaluationResult
            Evaluation result
        output_path : str
            Path to output Markdown file
        model_name : str, optional
            Model name for report title
        include_recommendations : bool, optional
            Whether to include recommendations (default: True)

        Examples
        --------
        >>> generator = ReportGenerator()
        >>> generator.generate_report(result, "report.md", model_name="bert-turkish")
        """
        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)

        summary = result.get_summary()
        lines = []

        # Title and header
        model_title = f" - {model_name}" if model_name else ""
        lines.append(f"# Semantic Evaluation Report{model_title}")
        lines.append("")
        lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        lines.append(f"**Total Runtime:** {summary['total_runtime']:.2f}s")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Executive Summary
        lines.extend(self._generate_executive_summary(summary))
        lines.append("")

        # Test Configuration
        lines.append("## Test Configuration")
        lines.append("")
        metadata = summary["metadata"]
        lines.append(f"- **Test Version:** {metadata.get('version', 'N/A')}")
        lines.append(f"- **Description:** {metadata.get('description', 'N/A')}")
        lines.append(f"- **Language:** {metadata.get('language', 'N/A')}")
        if metadata.get("domain"):
            lines.append(f"- **Domain:** {metadata['domain']}")
        lines.append(f"- **Tasks Completed:** {len(summary['tasks'])}")
        lines.append("")
        lines.append("---")
        lines.append("")

        # Detailed Task Results
        lines.append("## Detailed Task Results")
        lines.append("")

        for task_name, task_info in summary["tasks"].items():
            lines.extend(self._generate_task_section(task_name, task_info))
            lines.append("")

        # Recommendations (if enabled)
        if include_recommendations:
            lines.append("---")
            lines.append("")
            lines.extend(self._generate_recommendations(summary))
            lines.append("")

        # Footer
        lines.append("---")
        lines.append("")
        lines.append("*Report generated by SemEval Framework*")
        lines.append("")

        # Write file
        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))

        print(f"✅ Comprehensive report generated: {output_path}")

    def _generate_executive_summary(self, summary: Dict[str, Any]) -> List[str]:
        """Generate executive summary section."""
        lines = []
        lines.append("## Executive Summary")
        lines.append("")

        # Count successes and failures
        tasks = summary["tasks"]
        successful = sum(1 for t in tasks.values() if t["status"] == "success")
        failed = sum(1 for t in tasks.values() if t["status"] == "failed")

        lines.append(
            f"### Overall Status: {'✅ PASS' if failed == 0 else '⚠️ ISSUES DETECTED'}"
        )
        lines.append("")
        lines.append(f"- **Successful Tasks:** {successful}/{len(tasks)}")
        lines.append(f"- **Failed Tasks:** {failed}/{len(tasks)}")
        lines.append(f"- **Total Evaluation Time:** {summary['total_runtime']:.2f}s")
        lines.append("")

        # Task-specific highlights
        if successful > 0:
            lines.append("### Key Metrics Summary")
            lines.append("")

            for task_name, task_info in tasks.items():
                if task_info["status"] == "success":
                    metrics = task_info["metrics"]

                    if task_name == "information_retrieval":
                        ndcg = metrics.get("cosine-NDCG@10", 0)
                        status_icon = (
                            "🟢" if ndcg >= 0.7 else "🟡" if ndcg >= 0.5 else "🔴"
                        )
                        lines.append(
                            f"- **Information Retrieval:** {status_icon} NDCG@10 = {ndcg:.4f}"
                        )

                    elif task_name == "semantic_similarity":
                        accuracy = metrics.get("accuracy", 0)
                        status_icon = (
                            "🟢"
                            if accuracy >= 0.85
                            else "🟡" if accuracy >= 0.7 else "🔴"
                        )
                        lines.append(
                            f"- **Semantic Similarity:** {status_icon} Accuracy = {accuracy:.2%}"
                        )

            lines.append("")

        return lines

    def _generate_task_section(
        self, task_name: str, task_info: Dict[str, Any]
    ) -> List[str]:
        """Generate detailed section for a task."""
        lines = []

        lines.append(f"### {task_name.replace('_', ' ').title()}")
        lines.append("")

        if task_info["status"] == "failed":
            lines.append("**Status:** ❌ FAILED")
            lines.append(f"**Error:** {task_info.get('error', 'Unknown error')}")
            lines.append("")
            return lines

        lines.append("**Status:** ✅ SUCCESS")
        lines.append(f"**Runtime:** {task_info['runtime']:.2f}s")
        lines.append("")

        metrics = task_info["metrics"]

        if task_name == "information_retrieval":
            lines.extend(self._format_ir_metrics(metrics))

        elif task_name == "semantic_similarity":
            lines.extend(self._format_similarity_metrics(metrics))

        return lines

    def _format_ir_metrics(self, metrics: Dict[str, Any]) -> List[str]:
        """Format Information Retrieval metrics."""
        lines = []

        lines.append("#### Performance Metrics")
        lines.append("")
        lines.append("| Metric | @1 | @3 | @5 | @10 |")
        lines.append("|--------|----|----|----|----|")

        # NDCG
        ndcg_row = "| **NDCG** |"
        for k in [1, 3, 5, 10]:
            val = metrics.get(f"cosine-NDCG@{k}", 0)
            ndcg_row += f" {val:.4f} |"
        lines.append(ndcg_row)

        # MRR
        mrr_row = "| **MRR** |"
        for k in [1, 3, 5, 10]:
            val = metrics.get(f"cosine-MRR@{k}", 0)
            mrr_row += f" {val:.4f} |"
        lines.append(mrr_row)

        # MAP
        map_row = "| **MAP** |"
        for k in [1, 3, 5, 10]:
            val = metrics.get(f"cosine-MAP@{k}", 0)
            map_row += f" {val:.4f} |"
        lines.append(map_row)

        lines.append("")

        # Analysis
        ndcg10 = metrics.get("cosine-NDCG@10", 0)
        lines.append("#### Analysis")
        lines.append("")
        if ndcg10 >= 0.8:
            lines.append("- ✅ **Excellent** retrieval performance (NDCG@10 ≥ 0.8)")
        elif ndcg10 >= 0.7:
            lines.append("- 🟢 **Good** retrieval performance (NDCG@10 ≥ 0.7)")
        elif ndcg10 >= 0.5:
            lines.append("- 🟡 **Moderate** retrieval performance (NDCG@10 ≥ 0.5)")
        else:
            lines.append("- 🔴 **Poor** retrieval performance (NDCG@10 < 0.5)")
        lines.append("")

        return lines

    def _format_similarity_metrics(self, metrics: Dict[str, Any]) -> List[str]:
        """Format Semantic Similarity metrics."""
        lines = []

        lines.append("#### Core Metrics")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| **Triplet Accuracy** | {metrics.get('accuracy', 0):.2%} |")
        lines.append(f"| **Average Margin** | {metrics.get('avg_margin', 0):+.3f} |")
        lines.append(
            f"| **Avg Positive Similarity** | {metrics.get('avg_positive_sim', 0):.3f} |"
        )
        lines.append(
            f"| **Avg Negative Similarity** | {metrics.get('avg_negative_sim', 0):.3f} |"
        )
        lines.append(f"| **Margin > 0.2** | {metrics.get('margin_gt_02', 0):.2%} |")
        lines.append("")

        # Difficulty breakdown
        if metrics.get("difficulty_breakdown"):
            lines.append("#### Performance by Difficulty")
            lines.append("")
            lines.append("| Difficulty | Accuracy | Count |")
            lines.append("|------------|----------|-------|")
            for diff, stats in sorted(metrics["difficulty_breakdown"].items()):
                lines.append(
                    f"| {diff.capitalize()} | {stats['accuracy']:.2%} | {stats['count']} |"
                )
            lines.append("")

        # Subcategory breakdown
        if metrics.get("subcategory_breakdown"):
            lines.append("#### Performance by Subcategory")
            lines.append("")
            lines.append("| Subcategory | Accuracy | Count |")
            lines.append("|-------------|----------|-------|")
            for subcat, stats in sorted(metrics["subcategory_breakdown"].items()):
                lines.append(
                    f"| {subcat} | {stats['accuracy']:.2%} | {stats['count']} |"
                )
            lines.append("")

        # Analysis
        accuracy = metrics.get("accuracy", 0)
        margin = metrics.get("avg_margin", 0)

        lines.append("#### Analysis")
        lines.append("")

        if accuracy >= 0.90:
            lines.append("- ✅ **Excellent** semantic discrimination (accuracy ≥ 90%)")
        elif accuracy >= 0.80:
            lines.append("- 🟢 **Good** semantic discrimination (accuracy ≥ 80%)")
        elif accuracy >= 0.70:
            lines.append("- 🟡 **Moderate** semantic discrimination (accuracy ≥ 70%)")
        else:
            lines.append("- 🔴 **Poor** semantic discrimination (accuracy < 70%)")

        if margin >= 0.3:
            lines.append(
                "- ✅ **Strong** separation between positive and negative examples"
            )
        elif margin >= 0.2:
            lines.append(
                "- 🟢 **Good** separation between positive and negative examples"
            )
        elif margin >= 0.1:
            lines.append(
                "- 🟡 **Moderate** separation between positive and negative examples"
            )
        else:
            lines.append(
                "- 🔴 **Weak** separation between positive and negative examples"
            )

        # Failed cases
        if metrics.get("failed_triplets_sample"):
            failed = metrics["failed_triplets_sample"]
            lines.append("")
            lines.append(f"**Failed Triplets:** {len(failed)} examples shown")
            lines.append("")

        lines.append("")

        return lines

    def _generate_recommendations(self, summary: Dict[str, Any]) -> List[str]:
        """Generate recommendations based on results."""
        lines = []
        lines.append("## Recommendations")
        lines.append("")

        recommendations = []

        for task_name, task_info in summary["tasks"].items():
            if task_info["status"] != "success":
                continue

            metrics = task_info["metrics"]

            if task_name == "information_retrieval":
                ndcg = metrics.get("cosine-NDCG@10", 0)
                if ndcg < 0.7:
                    recommendations.append(
                        "- 📊 **Information Retrieval:** Consider fine-tuning on domain-specific data to improve NDCG@10"
                    )
                elif ndcg < 0.8:
                    recommendations.append(
                        "- 💡 **Information Retrieval:** Performance is good, but could be improved with additional training data"
                    )

            elif task_name == "semantic_similarity":
                accuracy = metrics.get("accuracy", 0)
                margin = metrics.get("avg_margin", 0)

                if accuracy < 0.85:
                    recommendations.append(
                        "- 📊 **Semantic Similarity:** Triplet accuracy below threshold. Consider contrastive learning or triplet loss fine-tuning"
                    )

                if margin < 0.2:
                    recommendations.append(
                        "- 💡 **Semantic Similarity:** Low margin between positive and negative examples. Model needs better discrimination"
                    )

                # Check for difficulty patterns
                if metrics.get("difficulty_breakdown"):
                    diff_stats = metrics["difficulty_breakdown"]
                    for diff, stats in diff_stats.items():
                        if stats["accuracy"] < 0.7:
                            recommendations.append(
                                f"- ⚠️ **Semantic Similarity:** Poor performance on '{diff}' difficulty level ({stats['accuracy']:.1%})"
                            )

        if not recommendations:
            lines.append(
                "✅ **No specific recommendations.** The model performs well across all evaluated tasks."
            )
        else:
            lines.append("### Suggested Improvements")
            lines.append("")
            for rec in recommendations:
                lines.append(rec)

        lines.append("")

        return lines
